# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 2.0.11
_src_path: gh:algorandfoundation/algokit-fullstack-template
author_email: noerzamand@gmail.com
author_name: Delan Nurzaman
cloud_provider: none
contract_name: CobaFullStackWebTiga
preset_name: production
project_name: cobafullstackweb3

